### ISSUE TITLE
stringify breaks objects with circular references

### ISSUE THREAD

**Issue by tjstebbing** [brianoneil/curio#1]
Your debugging calls that use JSON.stringify throw errors for objects with circular references. Your actual library handles circular references without a problem if the debug calls are removed.

**Comment by raffecat** [comment]
Also, a performance warning: this approach will execute JSON.stringify in all those debug calls even when debugging is not turned on, which will add up quickly.

**Comment by brianoneil** [comment]
okay, fair point.  I am fine with removing them.  I will do it soon.  Sorry, I didn't see the notification for this issue until today.  I will leave this open until I get it updated.

**Comment by brianoneil** [comment]
okay, I didn't fix the actual stringify issue because I didn't want another dependency, but now unless you turn on curio:process in your debug env setting, it will not do the stringify call.  This addresses the potential perf issues when processing large amounts of data or large object graphs. This is in 0.2.0 and is published to npm now as well.
